pub const DEFAULT_TRAINING_QUERIES: &[&str] = &[
    "error handling",
    "authentication middleware",
    "database connection pooling",
    "retry with exponential backoff",
    "configuration loading",
    "async task spawning",
    "file parsing and validation",
    "request validation middleware",
    "logging and tracing setup",
    "memory allocation strategy",
    "test fixtures and mocking",
    "dependency injection pattern",
    "rate limiting implementation",
    "cache invalidation strategy",
    "serialization and deserialization",
    "graceful shutdown handling",
    "environment variable loading",
    "command line argument parsing",
    "HTTP client configuration",
    "TLS certificate validation",
    "database migration runner",
    "background job scheduling",
    "websocket connection handling",
    "JWT token validation",
    "password hashing and verification",
    "input sanitization",
    "pagination implementation",
    "search query parsing",
    "file upload handling",
    "email sending service",
    "webhook processing",
    "metrics collection",
    "health check endpoint",
    "circuit breaker pattern",
    "message queue consumer",
    "API versioning strategy",
    "CORS configuration",
    "request timeout handling",
    "connection pool management",
    "thread pool configuration",
    "mutex and lock management",
    "channel communication pattern",
    "iterator and stream processing",
    "binary serialization format",
    "compression and decompression",
    "cryptographic signing",
    "access control and permissions",
    "state machine implementation",
    "plugin architecture",
    "event sourcing pattern",
];
